# Generated by Django 4.1 on 2023-10-08 12:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('sku', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Единица складского учета')),
                ('group', models.CharField(max_length=32, verbose_name='Группа')),
                ('category', models.CharField(max_length=32, verbose_name='Категория')),
                ('subcategory', models.CharField(max_length=32, verbose_name='Подкатегория')),
                ('uom', models.PositiveSmallIntegerField(verbose_name='Маркер, обозначающий продаётся товар на вес или в ШТ')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Название')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
                ('division', models.CharField(max_length=32, verbose_name='Дивизион')),
                ('type_format', models.PositiveSmallIntegerField(verbose_name='Формат')),
                ('loc', models.PositiveSmallIntegerField(verbose_name='Тип локации')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Тип размера')),
                ('is_active', models.BooleanField(verbose_name='Флаг активного магазина на данный момент')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('sales_type', models.BooleanField(verbose_name='Флаг наличия промо')),
                ('sales_units', models.DecimalField(decimal_places=1, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Число проданных товаров без признака промо')),
                ('sales_units_promo', models.DecimalField(decimal_places=1, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Число проданных товаров с признаком промо')),
                ('sales_rub', models.DecimalField(decimal_places=1, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Продажи без признака промо в РУБ')),
                ('sales_run_promo', models.DecimalField(decimal_places=1, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Продажи с признаком промо в РУБ')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.category', verbose_name='Единица складского учета')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.store', verbose_name='Название магазина')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Дата расчета прогноза')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.category', verbose_name='Единица складского учета')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.store', verbose_name='Название магазина')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
            },
        ),
        migrations.CreateModel(
            name='DayForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('units', models.PositiveIntegerField(verbose_name='Спрос в ШТ')),
                ('forecast_sku_of_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='sale.forecast', verbose_name='Дата прогноза')),
            ],
            options={
                'verbose_name': 'Прогноз дня',
                'verbose_name_plural': 'Прогнозы дней',
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('store', 'sku', 'date'), name='unique_store_sku_date_in_sale'),
        ),
        migrations.AddConstraint(
            model_name='forecast',
            constraint=models.UniqueConstraint(fields=('store', 'sku', 'forecast_date'), name='unique_store_sku_fore_date_in_forecast'),
        ),
    ]
