# Generated by Django 4.1 on 2023-09-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('subcategory', models.CharField(max_length=200)),
                ('uom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('type_format', models.IntegerField()),
                ('loc', models.IntegerField()),
                ('size', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales_type', models.IntegerField()),
                ('sales_units', models.IntegerField()),
                ('sales_units_promo', models.IntegerField()),
                ('sales_rub', models.FloatField()),
                ('sales_run_promo', models.FloatField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.store')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('sales_units_forecasted', models.IntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.store')),
            ],
        ),
    ]
